# --------------------------------------
# Gitpod Config for Java + Maven + TestNG + LambdaTest Project
# --------------------------------------

image:
  file: .gitpod.Dockerfile

tasks:
  - name: Project Initialization
    init: |
      echo "🔧 Installing dependencies..."
      mvn -q -DskipTests clean install
    command: |
      echo "Gitpod Ready! To execute your Selenium tests on LambdaTest:"
      echo ""
      echo " Run: mvn test"
      echo ""

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.vscode-xml
    - humao.rest-client
    - mhutchie.git-graph

